# Generated by Django 4.2.7 on 2023-11-28 14:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Black_token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token1', models.CharField(db_index=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(db_index=True, default='', max_length=200)),
                ('email', models.EmailField(db_index=True, default='', max_length=254)),
                ('phone_no', models.CharField(db_index=True, default='', max_length=20)),
                ('first_name', models.CharField(db_index=True, default='', max_length=200)),
                ('last_name', models.CharField(db_index=True, default='', max_length=200)),
                ('subject', models.CharField(db_index=True, default='', max_length=200)),
                ('message', models.TextField(db_index=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='ipaddresshandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(db_index=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_info', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('visit_timestamp', models.DateTimeField()),
                ('leave_timestamp', models.DateTimeField(blank=True, null=True)),
                ('is_old_user', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, db_index=True, default='', max_length=254, null=True)),
                ('clinic_name', models.CharField(db_index=True, default='BackupDoc', max_length=100)),
                ('report', models.TextField(db_index=True)),
                ('date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai75589674.black_token')),
            ],
        ),
    ]
