# Generated by Django 4.2.7 on 2023-11-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai75589674', '0002_userreport_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreport',
            name='media',
            field=models.TextField(db_index=True, default=''),
        ),
    ]
