# Generated by Django 4.2.7 on 2023-12-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai75589674', '0003_alter_userreport_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='tmedia',
            field=models.TextField(blank=True, db_index=True, default='', null=True),
        ),
    ]
