# Generated by Django 4.2.7 on 2023-11-29 03:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('controler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_page',
            name='date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='about_page',
            name='title',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
    ]
