# Generated by Django 4.2.7 on 2023-11-29 04:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('controler', '0002_about_page_date_about_page_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privacy_Edit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, default='', max_length=100)),
                ('content', models.TextField(db_index=True, default='')),
                ('date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
