# Generated by Django 4.2.7 on 2023-11-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controler', '0003_privacy_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_page',
            name='image',
            field=models.FileField(db_index=True, default='', upload_to='e-pages/about'),
        ),
        migrations.AddField(
            model_name='privacy_edit',
            name='image',
            field=models.FileField(db_index=True, default='', upload_to='e-pages/privacy'),
        ),
    ]
